create table public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_email text not null,
  acao text not null,
  detalhe jsonb default '{}'::jsonb,
  ip text,
  created_at timestamptz default now()
);

alter table public.admin_logs enable row level security;

drop policy if exists "admin_logs_service_rw" on public.admin_logs;
create policy "admin_logs_service_rw"
  on public.admin_logs
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create index if not exists idx_admin_logs_email on public.admin_logs(admin_email);
create index if not exists idx_admin_logs_created on public.admin_logs(created_at desc);
